---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-job1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
spec:
{{/*  ttlSecondsAfterFinished: 100*/}}
  template:
    spec:
      containers:
        - name: presync-job1
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - |
              echo "Pre Sync Job 1 - Fail" ; exit 1
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-job2
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "2"
{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
spec:
{{/*  ttlSecondsAfterFinished: 100*/}}
  template:
    spec:
      containers:
        - name: presync-job2
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - |
              echo "Pre Sync Job 2"
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
spec:
{{/*  ttlSecondsAfterFinished: 100*/}}
  template:
    spec:
      containers:
        - name: postsync-job
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - |
              echo "Post Sync Job"
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: syncfail-job
  annotations:
    argocd.argoproj.io/hook: SyncFail
{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
spec:
{{/*  ttlSecondsAfterFinished: 100*/}}
  template:
    spec:
      containers:
        - name: syncfail-job
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "-H"
            - "Content-Type: application/json"
            - "-d"
            - "payload={\"status\": \"Failed\"}"
            - "http://echo-server:8080/echo"
      restartPolicy: Never
  backoffLimit: 2
