apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
        - name: webhook-receiver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: LOG_WITHOUT_NEWLINE
              value: "false"
          ports:
            - containerPort: 8080
