apiVersion: v1
kind: Service
metadata:
  name: hello-world-server-hook
spec:
  selector:
    app: hello-world-server-hook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # Match the port where your Go application is running
