apiVersion: batch/v1
kind: Job
metadata:
  generateName: argocd-post-sync-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: argocd-post-sync-test
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "--data-urlencode"
            - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
            - "http://echo-server:8080/echo"
      restartPolicy: Never
  backoffLimit: 2
