apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'hello-world-server'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: 'prod'
  source:
    path: 'chart/hello-world-server'
    repoURL: 'https://github.com/kenshin579/argocd-charts-sample'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
