apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server # Add this label
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: "{{ .Values.image.name_tag }}" # Use the image name and tag from values.yaml
          ports:
            - containerPort: 8080
